AWSTemplateFormatVersion: 2010-09-09
Description: Template to deploy opensearch and associated resources bastion host.

Parameters:
  TemplateBucket:
    Type: String
    Description: Name of the S3 bucket where stack files are being deployed
    Default: opensearch-templates-1234567890

  ProjectConstants:
    Type: String
    Description: Name of the file containing constants for the project
    Default: constants.yaml

  VPCStack:
    Type: String
    Description: Name of the vpc stack
    Default: networking

Mappings:
  ProjectParameters:
    'Fn::Transform':
      Name: 'AWS::Include'
      Parameters:
        Location: # s3://<TemplateBucket>/constants.yaml
          !Join
            - ''
            - - 's3://'
              - !Ref TemplateBucket
              - '/'
              - !Ref ProjectConstants

Resources:
  # Creates a S3 bucket to store raw (non-indexed) data
  RawRecordBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub
        - raw-data-${AccountNumber}
        - AccountNumber: !Ref AWS::AccountId

  # Create an OpenSearch Service Domain
  OpenSearchDomain:
    Type: AWS::Elasticsearch::Domain
    Properties:
      DomainName: !FindInMap [ProjectParameters, OpenSearch, DomainName]
      ElasticsearchVersion: 7.10
      ElasticsearchClusterConfig:
        InstanceType: !FindInMap [ProjectParameters, OpenSearch, OpenSearchInstanceType]
        InstanceCount: 1
      EBSOptions:
        EBSEnabled: true
        VolumeType: gp2
        VolumeSize: 10
      DomainEndpointOptions:
        EnforceHTTPS: true
      EncryptionAtRestOptions:
        Enabled: true
      NodeToNodeEncryptionOptions:
        Enabled: true
      AdvancedSecurityOptions:
        Enabled: true
        InternalUserDatabaseEnabled: true
        MasterUserOptions:
          MasterUserName: !FindInMap [ProjectParameters, OpenSearch, MasterUserName]
          MasterUserPassword: !FindInMap [ProjectParameters, OpenSearch, MasterUserPassword]
      VPCOptions:
        SubnetIds:
          Fn::ImportValue:
            !Join
              - ''
              - - !Ref VPCStack
                - "PublicSubnet"
        SecurityGroupIds:
          Fn::ImportValue:
            !Join
              - ''
              - - !Ref VPCStack
                - "OpenSearchSecurityGroup"
      AccessPolicies:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action: "es:*"
            Resource: 
              !Sub arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/${DomainName}/*



